apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  # SC-13 & SC-28: Integration of Key Vault with Kubernetes for secure key distribution
  name: azure-keyvault
  namespace: otto
spec:
  provider: azure
  secretObjects:
  # SC-8(1): Ensures that sensitive information is securely retrieved and used by the application
  - secretName: azure-keyvault-secrets
    type: Opaque
    data:
      - key: djangosecretkey
        objectName: DJANGO-SECRET-KEY
      - key: vectordbpasswordkey
        objectName: VECTORDB-PASSWORD
      - key: openaiservicekey
        objectName: OPENAI-SERVICE-KEY
      - key: cognitiveservicekey
        objectName: COGNITIVE-SERVICE-KEY
      - key: storageaccountkey
        objectName: STORAGE-KEY
      - key: djangodbhostkey
        objectName: DJANGODB-HOSTNAME
      - key: djangodbpasswordkey
        objectName: DJANGODB-PASSWORD
      - key: entraclientsecretkey
        objectName: ENTRA-CLIENT-SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${AKS_IDENTITY_ID}"
    keyvaultName: "${KEYVAULT_NAME}"
    objects: |
      array:
        - |
          objectName: DJANGO-SECRET-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: VECTORDB-PASSWORD
          objectType: secret 
          objectVersion: ""
        - |
          objectName: COGNITIVE-SERVICE-KEY
          objectType: secret   
          objectVersion: ""
        - |
          objectName: OPENAI-SERVICE-KEY
          objectType: secret   
          objectVersion: ""      
        - |
          objectName: STORAGE-KEY
          objectType: secret  
          objectVersion: ""      
        - |
          objectName: DJANGODB-HOSTNAME
          objectType: secret
          objectVersion: "" 
        - |
          objectName: DJANGODB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: ENTRA-CLIENT-SECRET
          objectType: secret
          objectVersion: ""
    tenantId: "${TENANT_ID}"
